# Data Collection

In [8]:
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\arnav\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


# Importing Libraries

In [21]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from sklearn.model_selection import train_test_split

# Tokenizing data

In [10]:
data = gutenberg.raw('shakespeare-hamlet.txt')

with open ('hamlet.txt', 'w') as file:
    file.write(data)

In [11]:
with open ('hamlet.txt', 'r') as file:
    text = file.read().lower()

In [12]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts([text])
total_words = len(tokenizer.word_index) + 1
print(total_words)

4818


# Creating input sequences

In [13]:
text = text.split('\n')
text

['[the tragedie of hamlet by william shakespeare 1599]',
 '',
 '',
 'actus primus. scoena prima.',
 '',
 'enter barnardo and francisco two centinels.',
 '',
 "  barnardo. who's there?",
 '  fran. nay answer me: stand & vnfold',
 'your selfe',
 '',
 '   bar. long liue the king',
 '',
 '   fran. barnardo?',
 '  bar. he',
 '',
 '   fran. you come most carefully vpon your houre',
 '',
 "   bar. 'tis now strook twelue, get thee to bed francisco",
 '',
 "   fran. for this releefe much thankes: 'tis bitter cold,",
 'and i am sicke at heart',
 '',
 '   barn. haue you had quiet guard?',
 '  fran. not a mouse stirring',
 '',
 '   barn. well, goodnight. if you do meet horatio and',
 'marcellus, the riuals of my watch, bid them make hast.',
 'enter horatio and marcellus.',
 '',
 "  fran. i thinke i heare them. stand: who's there?",
 '  hor. friends to this ground',
 '',
 '   mar. and leige-men to the dane',
 '',
 '   fran. giue you good night',
 '',
 "   mar. o farwel honest soldier, who hath reli

In [14]:
input_sequences = []

for line in text:
    token_list = tokenizer.texts_to_sequences([line])[0]

    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [17]:
padded_sequences = pad_sequences(input_sequences)
padded_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

# Splitting train and test data

In [19]:
x = padded_sequences[:,:-1]
y = padded_sequences[:, -1]

In [22]:
y = tf.keras.utils.to_categorical(y)

In [23]:
print(x)
print()
print(y)

[[   0    0    0 ...    0    0    1]
 [   0    0    0 ...    0    1  687]
 [   0    0    0 ...    1  687    4]
 ...
 [   0    0    0 ...  687    4   45]
 [   0    0    0 ...    4   45 1047]
 [   0    0    0 ...   45 1047    4]]

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [24]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)